`read.Data` <-
function(blocksperarray=4,spotter="arrayjet",writetable=FALSE){
          ## read gprfiles
            temp.dat <-  read.gpr(blocksperarray)
          ## replace ID if gal is generated by aushon
            if (spotter=="aushon") {
             temp.dat <- sub.ID(temp.dat)
            }
            incubation <- read.slidedescription()
            temp.dat.i <- annotate.arrays (temp.dat,incubation)
            sampleID <- read.sampledescription()
            temp.dat.ii <- annotate.samples(temp.dat.i,sampleID)
            
            if(writetable){
            write.Data(temp.dat.ii)
            }
            
            return(temp.dat.ii)
}

